export default {
  21: { key: 21, name: "Barrier", id: "SummonerBarrier" },
  1: { key: 1, name: "Cleanse", id: "SummonerBoost" },
  2202: { key: 2202, name: "Flash", id: "SummonerCherryFlash" },
  2201: { key: 2201, name: "Flee", id: "SummonerCherryHold" },
  14: { key: 14, name: "Ignite", id: "SummonerDot" },
  3: { key: 3, name: "Exhaust", id: "SummonerExhaust" },
  4: { key: 4, name: "Flash", id: "SummonerFlash" },
  6: { key: 6, name: "Ghost", id: "SummonerHaste" },
  7: { key: 7, name: "Heal", id: "SummonerHeal" },
  13: { key: 13, name: "Clarity", id: "SummonerMana" },
  30: { key: 30, name: "To the King!", id: "SummonerPoroRecall" },
  31: { key: 31, name: "Poro Toss", id: "SummonerPoroThrow" },
  11: { key: 11, name: "Smite", id: "SummonerSmite" },
  39: { key: 39, name: "Mark", id: "SummonerSnowURFSnowball_Mark" },
  32: { key: 32, name: "Mark", id: "SummonerSnowball" },
  12: { key: 12, name: "Teleport", id: "SummonerTeleport" },
  54: { key: 54, name: "Placeholder", id: "Summoner_UltBookPlaceholder" },
  55: {
    key: 55,
    name: "Placeholder and Attack-Smite",
    id: "Summoner_UltBookSmitePlaceholder",
  },
} as { [key: number]: { key: number; name: string; id: string } };
