import { Champion } from "../lib/types/common";

export default [
  { id: 266, name: "Aatrox", lanes: ["top", "jungle"] },
  { id: 103, name: "Ahri", lanes: ["mid", "top", "bot"] },
  { id: 84, name: "Akali", lanes: ["mid", "top"] },
  { id: 166, name: "Akshan", lanes: ["mid", "top", "bot"] },
  { id: 12, name: "Alistar", lanes: ["support", "top"] },
  { id: 799, name: "Ambessa", lanes: ["top", "mid", "jungle"] },
  { id: 32, name: "Amumu", lanes: ["jungle", "support"] },
  { id: 34, name: "Anivia", lanes: ["mid", "support"] },
  { id: 1, name: "Annie", lanes: ["mid", "support"] },
  { id: 523, name: "Aphelios", lanes: ["bot"] },
  { id: 22, name: "Ashe", lanes: ["bot", "support"] },
  { id: 136, name: "AurelionSol", lanes: ["mid", "top"] },
  { id: 893, name: "Aurora", lanes: ["mid", "top"] },
  { id: 268, name: "Azir", lanes: ["mid", "top"] },
  { id: 432, name: "Bard", lanes: ["support", "top"] },
  { id: 200, name: "Belveth", lanes: ["jungle"] },
  { id: 53, name: "Blitzcrank", lanes: ["support"] },
  { id: 63, name: "Brand", lanes: ["support", "mid"] },
  { id: 201, name: "Braum", lanes: ["support"] },
  { id: 51, name: "Caitlyn", lanes: ["bot"] },
  { id: 164, name: "Camille", lanes: ["top", "support", "jungle"] },
  { id: 69, name: "Cassiopeia", lanes: ["mid", "top", "bot"] },
  { id: 31, name: "Chogath", lanes: ["top", "mid"] },
  { id: 42, name: "Corki", lanes: ["bot", "mid"] },
  { id: 122, name: "Darius", lanes: ["top", "mid"] },
  { id: 131, name: "Diana", lanes: ["jungle", "mid"] },
  { id: 119, name: "Draven", lanes: ["bot"] },
  { id: 36, name: "DrMundo", lanes: ["top", "jungle"] },
  { id: 245, name: "Ekko", lanes: ["mid", "jungle"] },
  { id: 60, name: "Elise", lanes: ["jungle", "support"] },
  { id: 28, name: "Evelynn", lanes: ["jungle"] },
  { id: 81, name: "Ezreal", lanes: ["bot", "mid"] },
  { id: 9, name: "Fiddlesticks", lanes: ["jungle", "support"] },
  { id: 114, name: "Fiora", lanes: ["top"] },
  { id: 105, name: "Fizz", lanes: ["mid", "top"] },
  { id: 3, name: "Galio", lanes: ["mid", "support", "top"] },
  { id: 41, name: "Gangplank", lanes: ["top", "mid"] },
  { id: 86, name: "Garen", lanes: ["top", "mid"] },
  { id: 150, name: "Gnar", lanes: ["top"] },
  { id: 79, name: "Gragas", lanes: ["jungle", "top", "mid"] },
  { id: 104, name: "Graves", lanes: ["jungle", "top"] },
  { id: 887, name: "Gwen", lanes: ["top", "jungle"] },
  { id: 120, name: "Hecarim", lanes: ["jungle"] },
  { id: 74, name: "Heimerdinger", lanes: ["top", "support", "mid"] },
  { id: 910, name: "Hwei", lanes: ["mid", "bottom", "top"] },
  { id: 420, name: "Illaoi", lanes: ["top"] },
  { id: 39, name: "Irelia", lanes: ["top", "mid"] },
  { id: 427, name: "Ivern", lanes: ["jungle", "support"] },
  { id: 40, name: "Janna", lanes: ["support"] },
  { id: 59, name: "JarvanIV", lanes: ["jungle", "top"] },
  { id: 24, name: "Jax", lanes: ["top", "jungle"] },
  { id: 126, name: "Jayce", lanes: ["top", "mid"] },
  { id: 202, name: "Jhin", lanes: ["bot"] },
  { id: 222, name: "Jinx", lanes: ["bot"] },
  { id: 145, name: "Kaisa", lanes: ["bot", "top"] },
  { id: 429, name: "Kalista", lanes: ["bot"] },
  { id: 43, name: "Karma", lanes: ["support", "mid"] },
  { id: 30, name: "Karthus", lanes: ["jungle", "bot", "mid"] },
  { id: 38, name: "Kassadin", lanes: ["mid"] },
  { id: 55, name: "Katarina", lanes: ["mid"] },
  { id: 10, name: "Kayle", lanes: ["top", "mid"] },
  { id: 141, name: "Kayn", lanes: ["jungle"] },
  { id: 85, name: "Kennen", lanes: ["top", "mid"] },
  { id: 121, name: "Khazix", lanes: ["jungle"] },
  { id: 203, name: "Kindred", lanes: ["jungle"] },
  { id: 240, name: "Kled", lanes: ["top"] },
  { id: 96, name: "KogMaw", lanes: ["bot", "mid"] },
  { id: 897, name: "KSante", lanes: ["top", "support"] },
  { id: 7, name: "Leblanc", lanes: ["mid"] },
  { id: 64, name: "LeeSin", lanes: ["jungle"] },
  { id: 89, name: "Leona", lanes: ["support"] },
  { id: 876, name: "Lillia", lanes: ["jungle", "top"] },
  { id: 127, name: "Lissandra", lanes: ["mid", "top"] },
  { id: 236, name: "Lucian", lanes: ["bot", "mid"] },
  { id: 117, name: "Lulu", lanes: ["support", "mid"] },
  { id: 99, name: "Lux", lanes: ["support", "mid"] },
  { id: 54, name: "Malphite", lanes: ["top", "support"] },
  { id: 90, name: "Malzahar", lanes: ["mid", "support"] },
  { id: 57, name: "Maokai", lanes: ["top", "support"] },
  { id: 11, name: "MasterYi", lanes: ["jungle"] },
  { id: 800, name: "Mel", lanes: ["support", "bot", "mid"] },
  { id: 902, name: "Milio", lanes: ["support"] },
  { id: 21, name: "MissFortune", lanes: ["bot", "support"] },
  { id: 82, name: "Mordekaiser", lanes: ["top", "jungle"] },
  { id: 25, name: "Morgana", lanes: ["support", "mid"] },
  { id: 950, name: "Naafiri", lanes: ["top", "mid"] },
  { id: 267, name: "Nami", lanes: ["support"] },
  { id: 75, name: "Nasus", lanes: ["top", "jungle", "mid"] },
  { id: 111, name: "Nautilus", lanes: ["support", "top", "jungle"] },
  { id: 518, name: "Neeko", lanes: ["support", "mid"] },
  { id: 76, name: "Nidalee", lanes: ["jungle", "top"] },
  { id: 895, name: "Nilah", lanes: ["bot"] },
  { id: 56, name: "Nocturne", lanes: ["jungle", "top"] },
  { id: 20, name: "Nunu", lanes: ["jungle", "support"] },
  { id: 2, name: "Olaf", lanes: ["top", "jungle"] },
  { id: 61, name: "Orianna", lanes: ["mid", "bot"] },
  { id: 516, name: "Ornn", lanes: ["top"] },
  { id: 80, name: "Pantheon", lanes: ["support", "mid", "top"] },
  { id: 78, name: "Poppy", lanes: ["top", "support", "jungle"] },
  { id: 555, name: "Pyke", lanes: ["support", "mid"] },
  { id: 246, name: "Qiyana", lanes: ["mid", "jungle"] },
  { id: 133, name: "Quinn", lanes: ["top", "mid", "support"] },
  { id: 497, name: "Rakan", lanes: ["support"] },
  { id: 33, name: "Rammus", lanes: ["jungle", "support"] },
  { id: 421, name: "Rek'sai", lanes: ["jungle"] },
  { id: 526, name: "Rell", lanes: ["support"] },
  { id: 888, name: "Renata", lanes: ["support"] },
  { id: 58, name: "Renekton", lanes: ["top", "mid"] },
  { id: 107, name: "Rengar", lanes: ["jungle", "top"] },
  { id: 92, name: "Riven", lanes: ["top", "mid"] },
  { id: 68, name: "Rumble", lanes: ["top", "mid"] },
  { id: 13, name: "Ryze", lanes: ["mid", "top"] },
  { id: 360, name: "Samira", lanes: ["bot", "top"] },
  { id: 113, name: "Sejuani", lanes: ["jungle", "top"] },
  { id: 235, name: "Senna", lanes: ["support", "bot"] },
  { id: 147, name: "Seraphine", lanes: ["support", "mid"] },
  { id: 875, name: "Sett", lanes: ["top", "mid"] },
  { id: 35, name: "Shaco", lanes: ["jungle", "support"] },
  { id: 98, name: "Shen", lanes: ["top", "support"] },
  { id: 102, name: "Shyvana", lanes: ["jungle", "top"] },
  { id: 27, name: "Singed", lanes: ["top"] },
  { id: 14, name: "Sion", lanes: ["top"] },
  { id: 15, name: "Sivir", lanes: ["bot"] },
  { id: 72, name: "Skarner", lanes: ["jungle"] },
  { id: 901, name: "Smolder", lanes: ["bot", "mid"] },
  { id: 37, name: "Sona", lanes: ["support"] },
  { id: 16, name: "Soraka", lanes: ["support"] },
  { id: 50, name: "Swain", lanes: ["support", "mid"] },
  { id: 517, name: "Sylas", lanes: ["mid", "top"] },
  { id: 134, name: "Syndra", lanes: ["mid", "bot", "top"] },
  { id: 223, name: "TahmKench", lanes: ["top", "support"] },
  { id: 163, name: "Taliyah", lanes: ["mid", "jungle"] },
  { id: 91, name: "Talon", lanes: ["mid", "jungle"] },
  { id: 44, name: "Taric", lanes: ["support"] },
  { id: 17, name: "Teemo", lanes: ["top"] },
  { id: 412, name: "Thresh", lanes: ["support"] },
  { id: 18, name: "Tristana", lanes: ["bot", "mid"] },
  { id: 48, name: "Trundle", lanes: ["jungle", "top"] },
  { id: 23, name: "Tryndamere", lanes: ["top"] },
  { id: 4, name: "TwistedFate", lanes: ["mid"] },
  { id: 29, name: "Twitch", lanes: ["bot", "jungle"] },
  { id: 77, name: "Udyr", lanes: ["jungle", "top"] },
  { id: 6, name: "Urgot", lanes: ["top"] },
  { id: 110, name: "Varus", lanes: ["bot", "mid"] },
  { id: 67, name: "Vayne", lanes: ["bot", "top"] },
  { id: 45, name: "Veigar", lanes: ["mid", "bot"] },
  { id: 161, name: "Velkoz", lanes: ["mid", "support"] },
  { id: 254, name: "Vi", lanes: ["jungle"] },
  { id: 234, name: "Viego", lanes: ["jungle"] },
  { id: 112, name: "Viktor", lanes: ["mid", "bot"] },
  { id: 8, name: "Vladimir", lanes: ["top", "mid"] },
  { id: 106, name: "Volibear", lanes: ["top", "jungle"] },
  { id: 19, name: "Warwick", lanes: ["jungle", "top"] },
  { id: 62, name: "MonkeyKing", lanes: ["jungle", "top"] },
  { id: 498, name: "Xayah", lanes: ["bot"] },
  { id: 101, name: "Xerath", lanes: ["support", "mid"] },
  { id: 5, name: "XinZhao", lanes: ["jungle"] },
  { id: 157, name: "Yasuo", lanes: ["mid", "top"] },
  { id: 777, name: "Yone", lanes: ["mid", "top"] },
  { id: 83, name: "Yorick", lanes: ["top"] },
  { id: 350, name: "Yuumi", lanes: ["support"] },
  { id: 154, name: "Zac", lanes: ["jungle", "top"] },
  { id: 238, name: "Zed", lanes: ["mid", "top"] },
  { id: 221, name: "Zeri", lanes: ["bot"] },
  { id: 115, name: "Ziggs", lanes: ["bot", "mid"] },
  { id: 26, name: "Zilean", lanes: ["support", "mid"] },
  { id: 142, name: "Zoe", lanes: ["mid", "support"] },
  { id: 143, name: "Zyra", lanes: ["support", "mid"] },
] as Champion[];
